In [32]:
# Import statements
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from statsmodels.tsa.stattools import acf

In [33]:
# 10 year age classes
def map_to_age_class(age):
    age_map = {
        '00_04': '00_09', '05_09': '00_09',
        '10_14': '10_19', '15_19': '10_19',
        '20_24': '20_29', '25_29': '20_29',
        '30_34': '30_39', '35_39': '30_39',
        '40_44': '40_49', '45_49': '40_49',
        '50_54': '50_59', '55_59': '50_59',
        '60_64': '60_69', '65_69': '60_69',
        '70_74': '70_79', '75_79': '70_79',
        '80_84': '80_89', '85_89': '80_89',
        '90+': '90+'
        # Add additional mappings as needed
    }
    return age_map.get(age, age)

pop_full = pd.read_csv('ONS-population_2021-08-05.csv')
pop_full = (pop_full[(~pop_full['age'].isin(['00_59', '60+', 'unassigned','18_64','ALL','65_84','6_17'])) & (pop_full['category']=='AGE_ONLY')]).drop(columns=['category','gender'])
pop_full = pop_full[pop_full['areaCode'].str.startswith('E')]
pop_full.rename(columns={'areaCode':'area_code'},inplace=True)
pop_full['age_class'] = pop_full['age'].apply(map_to_age_class)
pop_full.drop(columns='age',inplace=True)
pop_full = pop_full.groupby(['area_code','age_class']).sum().reset_index()

cases = pd.read_csv('ltla_2023-12-14 (1).csv')
cases = (cases[~cases['age'].isin(['00_59', '60+', 'unassigned'])]).drop(columns=['areaType','rollingSum','rollingRate'])
cases['date'] = pd.to_datetime(cases['date'])
cases = cases[cases['date'] <= pd.to_datetime('2021-12-31')]
cases['age_class'] = cases['age'].apply(map_to_age_class)
cases.set_index('date',inplace=True)
cases.drop(columns='age',inplace=True)
cases = cases.groupby(['areaCode','areaName','age_class','date']).sum().reset_index().set_index('date')
cases = cases.rename({'areaCode':'area_code','areaName':'area_name'},axis=1)
weekly_counts_total = cases.groupby(['area_code','area_name','age_class']).rolling(7).sum().reset_index()
weekly_counts_total

         area_code    area_name age_class       date  cases
0        E06000001   Hartlepool     00_09 2020-03-16    NaN
1        E06000001   Hartlepool     00_09 2020-03-17    NaN
2        E06000001   Hartlepool     00_09 2020-03-18    NaN
3        E06000001   Hartlepool     00_09 2020-03-19    NaN
4        E06000001   Hartlepool     00_09 2020-03-20    NaN
...            ...          ...       ...        ...    ...
2097855  E09000033  Westminster       90+ 2021-12-27   15.0
2097856  E09000033  Westminster       90+ 2021-12-28   16.0
2097857  E09000033  Westminster       90+ 2021-12-29   16.0
2097858  E09000033  Westminster       90+ 2021-12-30   11.0
2097859  E09000033  Westminster       90+ 2021-12-31   12.0

[2097860 rows x 5 columns]

In [31]:
# Convert incidence to a proportion to allow for cross-LTLA comparison
weekly_counts_region = weekly_counts_total.copy()
weekly_counts_region = pd.merge(weekly_counts_region,pop_full,on=['area_code','age_class'])
#weekly_counts_region['incidence'] = weekly_counts_region['cases'] / weekly_counts_region['population']

npis = pd.read_csv('England_LTLA_NHSER.csv')
npis = npis[['NHSER_name','LTLA_name']]
npis.rename(columns={'NHSER_name':'region','LTLA_name':'ltla20nm'},inplace=True)
npis.drop_duplicates(inplace=True)
manual_dat = pd.DataFrame({'ltla20nm': ['Wycombe','South Bucks','Chiltern','Aylesbury Vale','Cornwall and Isles of Scilly', 'Hackney and City of London'], \
                           'region': ['South East', 'South East', 'South East', 'South East', 'South West', 'London']})
npis = pd.concat([npis,manual_dat])

cases_region = pd.merge(cases.reset_index(), npis, left_on='area_name', right_on='ltla20nm')
cases_region.drop(columns='ltla20nm',inplace=True)

weekly_counts_region = pd.merge(weekly_counts_region, npis, left_on='area_name', right_on='ltla20nm')
weekly_counts_region.drop(columns=['ltla20nm','area_code','area_name'],inplace=True)
weekly_counts_region = weekly_counts_region[weekly_counts_region['date'] >= '2020-06-01']
weekly_counts_region = weekly_counts_region.groupby(['region','date','age_class']).sum().reset_index()
weekly_counts_region['incidence'] = weekly_counts_region['cases'] / weekly_counts_region['population']
national_mean_total = weekly_counts_region.groupby(['date', 'age_class'])['incidence'].mean().reset_index()
national_mean_total.rename(columns={'incidence': 'national_mean_incidence'}, inplace=True)
weekly_counts_region = pd.merge(weekly_counts_region, national_mean_total, on=['date', 'age_class'])
weekly_counts_region['detrended'] = weekly_counts_region['incidence'] - weekly_counts_region['national_mean_incidence']
weekly_counts_region

wide_data_total = weekly_counts_region.pivot(index='date', columns=['region','age_class'], values='detrended')
wide_data_incidence = weekly_counts_region.pivot(index='date', columns=['region','age_class'], values='incidence')

wide_data_incidence.to_csv('regional_wide_incidence_10year_full.csv')
wide_data_total.to_csv('regional_wide_total_10year_full.csv')
weekly_counts_region.to_csv('regional_weekly_total_10year_full.csv')

In [3]:
# Convert incidence to a proportion to allow for cross-LTLA comparison
weekly_counts_total = pd.merge(weekly_counts_total,pop_full,on=['area_code','age_class'])
weekly_counts_total['incidence'] = weekly_counts_total['cases'] / weekly_counts_total['population']

npis = pd.read_csv('England_LTLA_NHSER.csv')
npis = npis[['NHSER_name','LTLA_name']]
npis.rename(columns={'NHSER_name':'region','LTLA_name':'ltla20nm'},inplace=True)
npis.drop_duplicates(inplace=True)
manual_dat = pd.DataFrame({'ltla20nm': ['Wycombe','South Bucks','Chiltern','Aylesbury Vale','Cornwall and Isles of Scilly', 'Hackney and City of London'], \
                           'region': ['South East', 'South East', 'South East', 'South East', 'South West', 'London']})
npis = pd.concat([npis,manual_dat])

cases_region = pd.merge(cases.reset_index(), npis, left_on='area_name', right_on='ltla20nm')
cases_region.drop(columns='ltla20nm',inplace=True)

weekly_counts_total = pd.merge(weekly_counts_total, npis, left_on='area_name', right_on='ltla20nm')
weekly_counts_total.drop(columns='ltla20nm',inplace=True)

regional_mean_total = weekly_counts_total.groupby(['region', 'date', 'age_class'])['incidence'].mean().reset_index()
regional_mean_total.rename(columns={'incidence': 'regional_mean_incidence'}, inplace=True)
regional_mean_total

                region       date age_class  regional_mean_incidence
0      East of England 2020-02-03     00_09                      NaN
1      East of England 2020-02-03     10_19                      NaN
2      East of England 2020-02-03     20_29                      NaN
3      East of England 2020-02-03     30_39                      NaN
4      East of England 2020-02-03     40_49                      NaN
...                ...        ...       ...                      ...
48815       South West 2021-12-31     50_59                 0.011950
48816       South West 2021-12-31     60_69                 0.007921
48817       South West 2021-12-31     70_79                 0.005142
48818       South West 2021-12-31     80_89                 0.003847
48819       South West 2021-12-31       90+                 0.004588

[48820 rows x 4 columns]

In [16]:
weekly_counts_total = pd.merge(weekly_counts_total, regional_mean_total, on=['region', 'date', 'age_class'])
weekly_counts_total['detrended'] = weekly_counts_total['incidence'] - weekly_counts_total['regional_mean_incidence']
weekly_counts_total

,area_code,area_name,age_class,date,cases,population,incidence,region,regional_mean_incidence,detrended
0,E06000001,Hartlepool,00_09,2020-03-16,NaN,10921,NaN,North East and Yorkshire,6.097003e-07,NaN
1,E06000001,Hartlepool,00_09,2020-03-17,NaN,10921,NaN,North East and Yorkshire,0.000000e+00,NaN
2,E06000001,Hartlepool,00_09,2020-03-18,NaN,10921,NaN,North East and Yorkshire,2.887278e-06,NaN
3,E06000001,Hartlepool,00_09,2020-03-19,NaN,10921,NaN,North East and Yorkshire,2.616595e-06,NaN
4,E06000001,Hartlepool,00_09,2020-03-20,NaN,10921,NaN,North East and Yorkshire,2.995047e-06,NaN
...,...,...,...,...,...,...,...,...,...,...
2097855,E09000033,Westminster,90+,2021-12-27,15.0,1863,0.008052,London,8.779400e-03,-0.000728
2097856,E09000033,Westminster,90+,2021-12-28,16.0,1863,0.008588,London,1.016454e-02,-0.001576
2097857,E09000033,Westminster,90+,2021-12-29,16.0,1863,0.008588,London,1.148086e-02,-0.002893
2097858,E09000033,Westminster,90+,2021-12-30,11.0,1863,0.005904,London,1.303980e-02,-0.007135
2097859,E09000033,Westminster,90+,2021-12-31,12.0,1863,0.006441,London,1.359969e-02,-0.007158

In [17]:
weekly_counts_total[(weekly_counts_total.area_name == 'Hartlepool') & (weekly_counts_total.date == '2020-06-01')]

,area_code,area_name,age_class,date,cases,population,incidence,region,regional_mean_incidence,detrended
77,E06000001,Hartlepool,00_09,2020-06-01,2.0,10921,0.000183,North East and Yorkshire,0.000030,0.000153
733,E06000001,Hartlepool,10_19,2020-06-01,0.0,11108,0.000000,North East and Yorkshire,0.000051,-0.000051
1389,E06000001,Hartlepool,20_29,2020-06-01,2.0,11284,0.000177,North East and Yorkshire,0.000219,-0.000042
2045,E06000001,Hartlepool,30_39,2020-06-01,3.0,11834,0.000254,North East and Yorkshire,0.000221,0.000033
2701,E06000001,Hartlepool,40_49,2020-06-01,4.0,10690,0.000374,North East and Yorkshire,0.000200,0.000174
3357,E06000001,Hartlepool,50_59,2020-06-01,4.0,13597,0.000294,North East and Yorkshire,0.000232,0.000062
4013,E06000001,Hartlepool,60_69,2020-06-01,4.0,11203,0.000357,North East and Yorkshire,0.000159,0.000198
4669,E06000001,Hartlepool,70_79,2020-06-01,5.0,8205,0.000609,North East and Yorkshire,0.000203,0.000406
5325,E06000001,Hartlepool,80_89,2020-06-01,1.0,4146,0.000241,North East and Yorkshire,0.000718,-0.000477
5981,E06000001,Hartlepool,90+,2020-06-01,1.0,848,0.001179,North East and Yorkshire,0.001879,-0.000700

In [23]:
wide_data_total = weekly_counts_total.pivot(index='date', columns=['area_name','age_class'], values='detrended')
wide_data_incidence = weekly_counts_total.pivot(index='date', columns=['area_name','age_class'], values='incidence')

wide_data_incidence.to_csv('wide_incidence_10year_full.csv')
wide_data_total.to_csv('wide_total_10year_full.csv')
weekly_counts_total.to_csv('weekly_total_10year_full.csv')

In [18]:
pop_full = pd.read_csv('ONS-population_2021-08-05.csv')
pop_full = (pop_full[(~pop_full['age'].isin(['00_59', '60+', 'unassigned','18_64','ALL','65_84','6_17'])) & (pop_full['category']=='AGE_ONLY')]).drop(columns=['category','gender'])
pop_full = pop_full[pop_full['areaCode'].str.startswith('E')]
pop_full.rename(columns={'areaCode':'area_code'},inplace=True)


cases = pd.read_csv('ltla_2023-12-14 (1).csv')
cases = (cases[~cases['age'].isin(['00_59', '60+', 'unassigned'])]).drop(columns=['areaType','rollingSum','rollingRate'])
cases['date'] = pd.to_datetime(cases['date'])
cases = cases[cases['date'] <= pd.to_datetime('2021-12-31')]
cases.set_index('date',inplace=True)
cases.sort_index(inplace=True)
cases = cases.rename({'areaCode':'area_code','areaName':'area_name'},axis=1)
weekly_counts_total = cases.groupby(['area_code','area_name','age']).rolling(7).sum().reset_index()
weekly_counts_total

         area_code    area_name    age       date  cases
0        E06000001   Hartlepool  00_04 2020-03-16    NaN
1        E06000001   Hartlepool  00_04 2020-03-17    NaN
2        E06000001   Hartlepool  00_04 2020-03-18    NaN
3        E06000001   Hartlepool  00_04 2020-03-19    NaN
4        E06000001   Hartlepool  00_04 2020-03-20    NaN
...            ...          ...    ...        ...    ...
3985929  E09000033  Westminster    90+ 2021-12-27   15.0
3985930  E09000033  Westminster    90+ 2021-12-28   16.0
3985931  E09000033  Westminster    90+ 2021-12-29   16.0
3985932  E09000033  Westminster    90+ 2021-12-30   11.0
3985933  E09000033  Westminster    90+ 2021-12-31   12.0

[3985934 rows x 5 columns]

In [19]:
# Convert incidence to a proportion to allow for cross-LTLA comparison
weekly_counts_total = pd.merge(weekly_counts_total,pop_full,on=['area_code','age'])
weekly_counts_total['incidence'] = weekly_counts_total['cases'] / weekly_counts_total['population']

npis = pd.read_csv('England_LTLA_NHSER.csv')
npis = npis[['NHSER_name','LTLA_name']]
npis.rename(columns={'NHSER_name':'region','LTLA_name':'ltla20nm'},inplace=True)
npis.drop_duplicates(inplace=True)
manual_dat = pd.DataFrame({'ltla20nm': ['Wycombe','South Bucks','Chiltern','Aylesbury Vale','Cornwall and Isles of Scilly', 'Hackney and City of London'], \
                           'region': ['South East', 'South East', 'South East', 'South East', 'South West', 'London']})
npis = pd.concat([npis,manual_dat])

cases_region = pd.merge(cases.reset_index(), npis, left_on='area_name', right_on='ltla20nm')
cases_region.drop(columns='ltla20nm',inplace=True)

weekly_counts_total = pd.merge(weekly_counts_total, npis, left_on='area_name', right_on='ltla20nm')
weekly_counts_total.drop(columns='ltla20nm',inplace=True)

regional_mean_total = weekly_counts_total.groupby(['region', 'date', 'age'])['incidence'].mean().reset_index()
regional_mean_total.rename(columns={'incidence': 'regional_mean_incidence'}, inplace=True)
regional_mean_total

                region       date    age  regional_mean_incidence
0      East of England 2020-02-03  00_04                      NaN
1      East of England 2020-02-03  05_09                      NaN
2      East of England 2020-02-03  10_14                      NaN
3      East of England 2020-02-03  15_19                      NaN
4      East of England 2020-02-03  20_24                      NaN
...                ...        ...    ...                      ...
92753       South West 2021-12-31  70_74                 0.005350
92754       South West 2021-12-31  75_79                 0.004852
92755       South West 2021-12-31  80_84                 0.003891
92756       South West 2021-12-31  85_89                 0.003783
92757       South West 2021-12-31    90+                 0.004588

[92758 rows x 4 columns]

In [20]:
weekly_counts_total = pd.merge(weekly_counts_total, regional_mean_total, on=['region', 'date', 'age'])
weekly_counts_total['detrended'] = weekly_counts_total['incidence'] - weekly_counts_total['regional_mean_incidence']
weekly_counts_total

,area_code,area_name,age,date,cases,population,incidence,region,regional_mean_incidence,detrended
0,E06000001,Hartlepool,00_04,2020-03-16,NaN,5147,NaN,North East and Yorkshire,0.000000,NaN
1,E06000001,Hartlepool,00_04,2020-03-17,NaN,5147,NaN,North East and Yorkshire,0.000000,NaN
2,E06000001,Hartlepool,00_04,2020-03-18,NaN,5147,NaN,North East and Yorkshire,0.000006,NaN
3,E06000001,Hartlepool,00_04,2020-03-19,NaN,5147,NaN,North East and Yorkshire,0.000006,NaN
4,E06000001,Hartlepool,00_04,2020-03-20,NaN,5147,NaN,North East and Yorkshire,0.000005,NaN
...,...,...,...,...,...,...,...,...,...,...
3985929,E09000033,Westminster,90+,2021-12-27,15.0,1863,0.008052,London,0.008779,-0.000728
3985930,E09000033,Westminster,90+,2021-12-28,16.0,1863,0.008588,London,0.010165,-0.001576
3985931,E09000033,Westminster,90+,2021-12-29,16.0,1863,0.008588,London,0.011481,-0.002893
3985932,E09000033,Westminster,90+,2021-12-30,11.0,1863,0.005904,London,0.013040,-0.007135
3985933,E09000033,Westminster,90+,2021-12-31,12.0,1863,0.006441,London,0.013600,-0.007158

In [21]:
weekly_counts_total[(weekly_counts_total.area_name == 'Hartlepool') & (weekly_counts_total.date == '2020-06-01')]

,area_code,area_name,age,date,cases,population,incidence,region,regional_mean_incidence,detrended
77,E06000001,Hartlepool,00_04,2020-06-01,1.0,5147,0.000194,North East and Yorkshire,0.000033,0.000161
733,E06000001,Hartlepool,05_09,2020-06-01,1.0,5774,0.000173,North East and Yorkshire,0.000028,0.000145
1389,E06000001,Hartlepool,10_14,2020-06-01,0.0,5982,0.000000,North East and Yorkshire,0.000033,-0.000033
2045,E06000001,Hartlepool,15_19,2020-06-01,0.0,5126,0.000000,North East and Yorkshire,0.000070,-0.000070
2701,E06000001,Hartlepool,20_24,2020-06-01,1.0,5162,0.000194,North East and Yorkshire,0.000224,-0.000030
3357,E06000001,Hartlepool,25_29,2020-06-01,1.0,6122,0.000163,North East and Yorkshire,0.000215,-0.000052
4013,E06000001,Hartlepool,30_34,2020-06-01,1.0,6163,0.000162,North East and Yorkshire,0.000235,-0.000073
4669,E06000001,Hartlepool,35_39,2020-06-01,2.0,5671,0.000353,North East and Yorkshire,0.000206,0.000146
5325,E06000001,Hartlepool,40_44,2020-06-01,4.0,5055,0.000791,North East and Yorkshire,0.000178,0.000613
5981,E06000001,Hartlepool,45_49,2020-06-01,0.0,5635,0.000000,North East and Yorkshire,0.000218,-0.000218
6637,E06000001,Hartlepool,50_54,2020-06-01,1.0,6594,0.000152,North East and Yorkshire,0.000214,-0.000063
7293,E06000001,Hartlepool,55_59,2020-06-01,3.0,7003,0.000428,North East and Yorkshire,0.000250,0.000178
7949,E06000001,Hartlepool,60_64,2020-06-01,4.0,6031,0.000663,North East and Yorkshire,0.000188,0.000476
8605,E06000001,Hartlepool,65_69,2020-06-01,0.0,5172,0.000000,North East and Yorkshire,0.000126,-0.000126
9261,E06000001,Hartlepool,70_74,2020-06-01,0.0,5051,0.000000,North East and Yorkshire,0.000146,-0.000146
9917,E06000001,Hartlepool,75_79,2020-06-01,5.0,3154,0.001585,North East and Yorkshire,0.000287,0.001298
10573,E06000001,Hartlepool,80_84,2020-06-01,1.0,2582,0.000387,North East and Yorkshire,0.000607,-0.000220
11229,E06000001,Hartlepool,85_89,2020-06-01,0.0,1564,0.000000,North East and Yorkshire,0.000905,-0.000905
11885,E06000001,Hartlepool,90+,2020-06-01,1.0,848,0.001179,North East and Yorkshire,0.001879,-0.000700

In [35]:
wide_data_total = weekly_counts_total.pivot(index='date', columns=['area_name','age'], values='detrended')
wide_data_incidence = weekly_counts_total.pivot(index='date', columns=['area_name','age'], values='incidence')

wide_data_incidence.to_csv('wide_incidence_full.csv')
wide_data_total.to_csv('wide_total_full.csv')
npis.to_csv('ltla_to_nhs.csv')
weekly_counts_total.to_csv('weekly_total_full.csv')